### ISSUE TITLE
Create recipe

### ISSUE THREAD

**Issue by fredhawk** [chingu-voyage4/Bears-Team-16#10]
As a user I should be able to create a recipe

## Markup
- [x] create portions element
- [x] create cooktime element
- [x] create title element
- [x] create ingredients form element
- [x] create categories element
- [x] create step form element
- [ ] create image upload element
- [ ] create description element

## Styling
- [ ] style portions element
- [ ] style cooktime element
- [ ] style title element
- [ ] style ingredients form element
- [ ] style categories element
- [ ] style step form element
- [ ] style image upload element
- [ ] style description element
- [ ] animate ingredients form in and out
- [ ] animate steps in and out

### Frontend
- [ ] test portions input
- [ ] test cooktime input
- [ ] test title input
- [ ] test ingredients form input
- [ ] test categories input
- [ ] test step form input
- [ ] test image upload input
- [ ] test description element

### Backend
- [ ] test create recipe api.

## Functions
- [ ] Send information to backend.

## API
- [ ] create recipe on backend

**Comment by aaayumi** [comment]
- A user can add ingredients of recipe using input field.
- A user can add description of recipe using input field.
- A user can upload photos of recipe.
- A user can click 'Submit' button to complete the recipe.

**Comment by fredhawk** [comment]
I had a thought of adding "Steps" to this which would mean adding dynamic input to the form.
A user clicks a + button to add another step to the recipe to describe how to make it.
Such a thing could be employed to adding ingredients too. Tho I think Thinktwice had a suggestion on extracting that from the steps somehow.

**Comment by thinktwice13** [comment]
Sorry, didn't see this. The idea was:
- We show three inline inputs for each step of ingredients.
- We parse the main input text for numbers and corresponding units and fill the remaining two inputs with that (reason they are inputs is to let the users make corrections if needed)

The parsing thing could be a bit challenging, but the goal is to make it as user-friendly as possible. 

There is also a scenario where a user unintentionally skips a step.
In that case, it should be possible to reorder them. 
The other solution could be not to hide completed steps, but simply keep adding input fields until they decide to submit. (Like something i had in my [voting app](https://obscure-crag-96570.herokuapp.com/polls/new))
I like reordering more.

Any thoughts/better ideas?

In any case, that will be a fun part to work on.
