### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by fredhawk** [chingu-voyage4/Bears-Team-16#24]
A design for the app

- [x] Home
- [x] Landing page
- [x] Login / Register
- [x] Recipe list view
- [x] Recipe single view
- [x] User profile / Settings
- [x] Favorite view
- [x] Create / Edit recipe

https://www.figma.com/file/LSvrxxi43xEZRY9fvgnCcivh/RecipeApp?node-id=47%3A84

**Comment by fredhawk** [comment]
### Colors 
[Color schema](https://material.io/color/#!/?view.left=0&view.right=1&primary.color=FFECB3&secondary.color=9b4646)

### Background
Maybe use a gradient or a pattern. Thoughts?

### Fonts 
- Nunito - Headings
- Quicksand - Copy

### Logo thoughts
Someone biting something
Maybe animating it as site loads?

Have put a placeholder for now.

### App name
- Bite sized

**Comment by fredhawk** [comment]
[Link to what Homepage looks like atm](https://www.figma.com/file/LSvrxxi43xEZRY9fvgnCcivh/RecipeApp?node-id=47%3A84)

**Comment by aaayumi** [comment]
+1 for gradient.

"Get a taste of heaven" is hard to read. I think it's better to format in one line, or at least align in two lines.

**Comment by thinktwice13** [comment]
My thoughts:
Clear > pattern > gradient background
no preference on fonts atm
+1 for the logo idea
I like the app name (although it implies tiny meals and already exists, but I don't think that matters for the voyage)

**Comment by fredhawk** [comment]
Cool well its mostly placeholders. Maybe bear sized would fit better?
Btw what do you mean with clear > pattern > gradient? Which is preferred? :grinning:

**Comment by thinktwice13** [comment]
@osycon For backgrounds, I like fill colors or low contrast patterns over the other options. 
Ultimately, I don't care really. Just saying since you asked :)

**Comment by fredhawk** [comment]
Ah then I'm with you. 😁

**Comment by thomaslombart** [comment]
I like the colors but it seems maybe a bit too dark! 

Like @aaayumi said, the text is hard to read and should be in one line. Otherwise, good job! 👍

**Comment by thinktwice13** [comment]
https://www.figma.com/file/LSvrxxi43xEZRY9fvgnCcivh/RecipeApp?node-id=47%3A84
