### ISSUE TITLE
Add landing page

### ISSUE THREAD

**Issue by thomaslombart** [chingu-voyage4/Bears-Team-16#43]
We should have a landing page to show the features of the app

**Comment by thomaslombart** [comment]
@thinktwice13, @aaayumi, @osycon I've built a landing page a few months ago. I thought that we could reuse this page for our recipe app. 
You can find it [here](https://thomlom.github.io/projects/landing-page/index.html)

The content is not important, just the design matters. What do you think of it ?

**Comment by aaayumi** [comment]
Nice! I also think that the design matters but some parts can be reused.
