### ISSUE TITLE
Proposal: Login/Signup process

### ISSUE THREAD

**Issue by thinktwice13** [chingu-voyage4/Bears-Team-16#46]
Combine Login/Sign up buttons (maybe called **Sign in**)
-  On click, load a login page and only show a single input field expecting an email or a username (later also SSO buttons from facebook, google etc).
- On submit, check for existing users and continue accordingly:
    - Show a password input field to existing users (later also a magic link button)
    - Redirect to signup page for new users

A slight twist - instead of having two paths, use login and signup components on a single path.

It was inspired by osycon's idea to add ingredients step-by-step. Probably we can reuse most of logic for both of these. 

Any thoughts?

**Comment by thomaslombart** [comment]
It's a great idea! If we want to use the same logic, higher order components will do the work.

**Comment by fredhawk** [comment]
I thought of having it on the same page maybe?
On one side showing the login and on the other side a button "register" or something, when it is pressed the login side slides to the right and changes to register form. This while the left side says " Already have an account. I want to log in"

Is that an option to explore perhaps? I saw something similar a while back and it looked pretty cool.

**Comment by fredhawk** [comment]
It wouldn't change the process but would change the look and feel of it I think.

**Comment by aaayumi** [comment]
It's a good idea, but I think it's better to say if it's login process or register process.
This website has 'Signin' button but a user can also choose 'signup' option from the screen.
![Screen Shot 2018-03-06 at 07.52.59.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a8810db88dee30011a92455/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f56b7191a378e80c2e53415a47be5d4a1f06a3a3dc78e2a436628f0d03b8826d5b27953816aeec831fbf03bf28831c8db2be9850d2aa6c7bb3d4d216744b470a83ed5c32aa984eca58f54ae84c5ca3153767f43b.png)

**Comment by thinktwice13** [comment]
@osycon Yeah, that does looks cooler than a single input. 
My idea came from the fact that I often forget if I have an account with the service and having the app check that first is a big UX +1 from me. ([Tumblr](https://www.tumblr.com/login) does that right).
I definitely like having it on the same page and that's what I meant by *on single path*.
Going with your idea, could we check for existing emails before the user submits the form (as soon as the email field loses focus)? That would be a happy compromise for me.

@aaayumi I agree, it should be obvious if you're logging in or signing up at any time. 
The goal of my idea was to check for the email as soon as possible and switch automatically to (or offer the user) an appropriate process. I would like to have at least some variant of that functionality.

**Comment by fredhawk** [comment]
@thinktwice13 agreed that should be possible.

@aaayumi yep it should always be clear where the user is.

**Comment by thomaslombart** [comment]
I like how Tumblr handles the login/signup process. I agree more with @thinktwice13, checking if the user has first an account is a + UX-wise.

This is the way I see things : 

1. There is a "box" with a title "Get Started" or something like this and an input field. 
2. The user types its email.
3. The user has already an account, the title changes to "Welcome back, ${username}" (then the user knows he has an account), the input disappears, and the password input appears.
3 Bis. The user doesn't have an account, the title changes to "Register an account to get started", the signup form appears.

If we have time, we can even explore a way to sign in like Medium does with their links sent by mail.

**Comment by fredhawk** [comment]
That's a great suggestion. Think I misunderstood it. But yes that is better ux.

**Comment by aaayumi** [comment]
I misunderstood it either. I checked tumblr now and it looks super cool.
