### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by fredhawk** [chingu-voyage4/Bears-Team-16#8]
As a user I should be able to authenticate myself and log in.

**Comment by fredhawk** [comment]
Early routing and some boilerplate up now. Still needs testing and connection to database and figuring out how secrets work.

**Comment by thinktwice13** [comment]
https://github.com/chingu-voyage4/Bears-Team-16/commit/c7ac5c5ab87bd1d3550b1aa9887c61c9ef159d78
- User returns from  `/login` route
- Added `JWT_SECRET` to config keys
- Added `createUser` resolver. `{email: mycoolnewemail@mail.com, password: mycoolestnewpassword}`

**Comment by thinktwice13** [comment]
017a2544c01d30a8424ce25eb6122c3889bdd8db
