### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by fredhawk** [chingu-voyage4/Bears-Team-16#9]
As a user I should be able to register with email and password and/or through Facebook, google, twitter

**Comment by aaayumi** [comment]
Condition for password  (any other idea/suggestion?)
- minimum 8 characters 
- Must have at least 1 number 
- Must have at least 1 nonalphanumeric characters: ~!@#$%^&*_-+=`|\(){}[]:;"'<>,.?/
- Must have at least 1 uppercase letter

**Comment by fredhawk** [comment]
Think that is sensible and pretty much standard.

**Comment by thinktwice13** [comment]
Up for that :+1: 
Seems strict, so I suggest having some kind of a hint component to make it easier for users. 
We could visually update it through form validation as user meet the conditions.

**Comment by thinktwice13** [comment]
017a2544c01d30a8424ce25eb6122c3889bdd8db
